// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fnnls_cpp
Eigen::VectorXd fnnls_cpp(const Eigen::MatrixXd& XtX, const Eigen::VectorXd& Xty, const double tol, const int max_iter, const bool sum_to_constant, const double constant, const bool lower_bound, const double lb);
RcppExport SEXP _nnsolve_fnnls_cpp(SEXP XtXSEXP, SEXP XtySEXP, SEXP tolSEXP, SEXP max_iterSEXP, SEXP sum_to_constantSEXP, SEXP constantSEXP, SEXP lower_boundSEXP, SEXP lbSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type XtX(XtXSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type Xty(XtySEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const bool >::type sum_to_constant(sum_to_constantSEXP);
    Rcpp::traits::input_parameter< const double >::type constant(constantSEXP);
    Rcpp::traits::input_parameter< const bool >::type lower_bound(lower_boundSEXP);
    Rcpp::traits::input_parameter< const double >::type lb(lbSEXP);
    rcpp_result_gen = Rcpp::wrap(fnnls_cpp(XtX, Xty, tol, max_iter, sum_to_constant, constant, lower_bound, lb));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_nnsolve_fnnls_cpp", (DL_FUNC) &_nnsolve_fnnls_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_nnsolve(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
