# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fnnls_cpp <- function(XtX, Xty, tol = 1e-6, max_iter = 1000L, sum_to_constant = FALSE, constant = 1.0, lower_bound = FALSE, lb = 0.0) {
    .Call(`_nnsolve_fnnls_cpp`, XtX, Xty, tol, max_iter, sum_to_constant, constant, lower_bound, lb)
}

